language: ruby
sudo: false
rvm: 2.4.0

matrix:
  include:
    - rvm: 2.4.0
      env: "BLACKLIGHT_VERSION=6.6.3"
    - rvm: 2.3.3
      env: "BLACKLIGHT_VERSION=5.17.2"

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
  - gem update --system
before_script:
  - jdk_switcher use oraclejdk8
