language: ruby
rvm:
  - 2.1
  - 2.0
  - 1.9.3

gemfile:
  - gemfiles/gemfile.rails3
  - gemfiles/gemfile.rails4

notifications:
  irc: "irc.freenode.org#projecthydra"
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
