language: ruby
cache: bundler
sudo: false
rvm:
  - 2.2

gemfile:
  - gemfiles/gemfile.rails4.1
  - gemfiles/gemfile.rails4.2

notifications:
  irc: "irc.freenode.org#projecthydra"
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_script:
  - jdk_switcher use oraclejdk8
