version: '3'

services:
  web:
    build: .
    volumes:
      - .:/data
    working_dir: /data/.internal_test_app
    command: sh -ic "pwd && bundle exec puma -b tcp://0.0.0.0:3000"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true