version: '3'

volumes:
  bundled:
  
services:
  web:
    build: .
    volumes:
      - .:/data
      - bundled:/usr/local/bundle
    command: /data/build/install_gems.sh
    command: sh -ic "cd /data/.internal_test_app && bundle exec puma -b tcp://0.0.0.0:3000"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true