version: '3.5'
services:
  app:
    build:
      context: .
      args:
        RAILS_ENV: development
        BUNDLE_WITHOUT: test
        APP_PATH: .dassie
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    volumes:
      - .dassie:/data
