version: '3.6'

services:
  solr:
    image: solr:7
    volumes:
      - ./solr/conf/:/myconfig
    # command: solr-create -c hydra-test -d /myconfig
    # ports:
    #  - 8985:8983
  # solr-valkyrie-test:
  #   image: solr:7
  #   volumes:
  #     - ./solr/conf/:/myconfig
  #   command: solr-create -c hyrax-valkyrie-test -d /myconfig
  #   ports:
  #     - 8987:8983
      # fcrepo:
  #   image: yinlinchen/fcrepo4-docker
  #   ports:
  #     - 8983:8080
  solr-test:
    extends: solr
    command: solr-create -c hydra-test -d /myconfig
    ports:
      - 8985:898
  redis:
    image: redis
    ports:
      - 6379:6379

