version: '3'

volumes:
  bundled:
  
services:
  web:
    build: .
    working_dir: /data/.internal_test_app
    volumes:
      - .:/data
      - bundled:/usr/local/bundle
    command: sh -ic "bundle exec puma -b tcp://0.0.0.0:3000"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true