version: '3'

services:
  web:
    build: .
    working_dir: /data/.internal_test_app
    volumes:
      - .:/data
      - bundled:/usr/local/bundle
    environment:
      SOLR_URL: http://solr-dev:8983/solr/hyrax-dev
      SOLR_CORE: hyrax-dev
    command: bash -ic "bundle exec puma -b tcp://0.0.0.0:3000"
    ports:
      - "3000:3000"
    depends_on:
      - solr-dev
    stdin_open: true
    tty: true

  ##
  # SOLR Index server
  solr-dev: &solr-dev
    image: solr:7-alpine
    ports:
      - "8983:8983"
    volumes:
      - solr-dev:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - hyrax-dev

volumes:
  bundled:
  solr-dev:

