attributes:
  title:
    type: string
    multiple: true
    index_keys:
      - "title_sim"
      - "title_tesim"
    form:
      required: true
      primary: true
      multiple: false
  alternative_title:
    type: string
    multiple: true
    form:
      primary: false
  date_modified:
    type: date_time
  date_uploaded:
    type: date_time
  depositor:
    type: string
